#ifndef LAB2_PRISONER_DILEMMA_CONSTANTS_H
#define LAB2_PRISONER_DILEMMA_CONSTANTS_H

enum {
    MAX_VAR = 8,
    STR_CNT = 7,
    STR_PLAY = 3,
    C = 0,
    D = 1
};

#endif //LAB2_PRISONER_DILEMMA_CONSTANTS_H
