#ifndef LAB2_PRISONER_DILEMMA_CONSTANTS_H
#define LAB2_PRISONER_DILEMMA_CONSTANTS_H

enum {
    MAX_VAR = 8,
    STR_CNT = 5,
    STR_PLAY = 3
};
//#define MAX_VAR 8
//#define STR_CNT 5
//#define STR_PLAY 3

#endif //LAB2_PRISONER_DILEMMA_CONSTANTS_H
